version: '3.8'

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile_postgresql
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: Dockerfile_python
    container_name: flask_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - database

volumes:
  postgres_data:
